### PR TITLE
Allow fetching a user by ID in admin API

### PR DESCRIPTION
**Pull request by MacTwister**
I'm creating a script where it would be useful to fetch users by ID. There already seems to be a GET user route, though it is using the username parameter. To not break compatibility, I thought to just adjust that if the key would be an integer, fetch record by ID. I am not a Ruby person, so not sure if this is the best way, but thought along these lines, the change, has the least disruption.

So the urls `/2/users/mactwister` or `/2/users/123456` would return the same user.

### CODE REVIEW

**Comment by viktorsmari** [comment]
Btw, Rails by default gives us the `.json` endpoints, is that something we could use?

So if you find your profile:
- https://fablabs.io/users/mactwister

You can add the `.json` to see your `id`
- https://fablabs.io/users/mactwister.json

And use the `id` directly in the url
- https://fablabs.io/users/30466.json

**Comment by MacTwister** [comment]
Interesting, that could work. If it makes sense, to also return the username there, then I can use the returned username with the API call 🙂

**Comment by viktorsmari** [comment]
I deployed the change, if you refresh https://fablabs.io/users/30466.json we should also see the `username`

What are you using the `username`s for in the scripts?

Because fablabs.io users can **change their usernames**

**Comment by MacTwister** [comment]
> I deployed the change, if you refresh https://fablabs.io/users/30466.json we should also see the `username`

Great, Thanks for speedie update 👍 

> Because fablabs.io users can **change their usernames** and email. So only the `id` is 'fixed'

Exactly, I'm just tracking IDs but sometimes still need username (ie. Nueval) 😄

**Pull request closed without merging**
