### PR TITLE
WIP: Use npm instead of bower

### PR DESCRIPTION
**Pull request by viktorsmari**
Bower is deprecated.
Now we install dependencies with npm instead. (`npm install`, now installs everything - tested and works)

### TODO:
- [ ] Remove bower.json

#### Not needed when dockerized:
- [ ] Do we need to add a new capistrano tasks for node_modules?
- [ ] See *config/deploy.rb:66*, remove all Bower related tasks

### CODE REVIEW

**Comment by openp2pdesign** [comment]
Bower is maintained but won't have future evolution, so it's not most important issue now (it can still be used) but something to consider anyway.

But NPM or [Yarn](https://yarnpkg.com/lang/en/) (as Bower suggests)?

**Comment by viktorsmari** [comment]
This also made the dockerization easier, where I had an issue with bower.

The only thing missing is I need to look into what bower was / is doing in the deploy process. When we migrate to use Docker in production, then that step won't matter, since we won't use a capistrano deploy process.

All in all, it is also nice to just do `npm install` and not also `bower install`

**Comment by viktorsmari** [comment]
This will be simpler when we reach Rails 5

**Comment by viktorsmari** [comment]
Done.

**Pull request closed without merging**
