### PR TITLE
Use CDN links

### PR DESCRIPTION
**Pull request by tuengominh**
Hi @viktorsmari 

The CDN links are working now on my local machine!

Thanks,

### CODE REVIEW

**Comment by viktorsmari** [comment]
Did you check the `app/views/layouts/*` files?

In that folder there are 4 files which load depending on the route/controller in use.

* The `application` file loads the `application/header` file that you changed.
* The `embed` does not
* The `session` does not load it
* The `welcome` loads it.

This means if you use the `session` controller (like when signing in), it probably won't load Bootstrap, because bootstrap is only loaded in the `head` file, resulting in visual errors

**Comment by tuengominh** [comment]
1. I saw it, I guess I came from here: https://getbootstrap.com/docs/4.0/components/tooltips/. It is also used in application.js.coffee, so I leave it like that for now :-?
2. It's true that the "sessions" layout is never used. I also tried deleting it and check around the website, no visual errors. So in my latest commit, I deleted it. For the "welcome" and "embed" layouts, some controllers are using them though.

**Comment by viktorsmari** [comment]
1. We should not merge when there are errors in the console.
* Is everything loaded in the correct order like they mention here:
* https://getbootstrap.com/docs/4.4/getting-started/introduction/
  > jQuery must come first, then Popper.js, and then our JavaScript plugins.
* Did you also check this: https://getbootstrap.com/docs/4.0/components/tooltips/
* Are we mixing 2 versions, 4.4.0 and 4.4.1?

* We are loading 2 versions of jQuery - is that OK?



2. Perfect.
Where is the embed layout used? I did not find. Did you test it?

**Comment by tuengominh** [comment]
Hi @viktorsmari 

1. I cleaned up unnecessary CDN links of JQuery & Bootstrap).  I'm following the order JQuery -> Bootrap bundle (incl. Popper) mentioned in the documentation. Regarding the link you mentioned, we're using the <script> tag, if I remove it we will get an error (Bootstrap requires JQuery). I also load Jquery once :-?
Screen Shot 2020-03-30 at 8 55 05 PM

Besides, when I tried to check which elements are using tooltip(), I see none. So should I just comment it out for now?
Screen Shot 2020-03-30 at 8 55 51 PM

2. I see the labs_controller.rb is calling render layout: 'embed' 

3. I think the current master branch is having another error: 
Screen Shot 2020-03-30 at 8 55 51 PM
Just want to check if you know about this :-?

**Pull request merged**
